import{a as m,S as L,i as n}from"./assets/vendor-D3eAW7nd.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const h of r.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&o(h)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const y=s=>`<li class="gallery-card">
     <a class="gallery-link" href="${s.largeImageURL}">
       <img class="gallery-img" src="${s.webformatURL}" alt="${s.tags}" width='360' height='200'; />
       <div class="image-info">
         <p>Likes <span>${s.likes}</span></p>
         <p>Views  <span>${s.views}</span></p>
         <p>Comments  <span>${s.comments}</span></p>
         <p>Downloads  <span>${s.downloads}</span></p>
       </div>
     </a>
   </li>`;m.defaults.baseURL="https://pixabay.com/api/";const f=(s,t)=>{const a={params:{key:"45727307-f96b67a5018b68fa33b524c91",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:t}};return m.get("",a)},u=document.querySelector(".js-input-form"),c=document.querySelector(".js-gallery"),p=document.querySelector(".js-loader"),l=document.querySelector(".js-load-more");let i=1,d="";const g=new L(".js-gallery a",{captionDelay:250,captionPosition:"bottom",captionsData:"alt",overlayOpacity:1});p.classList.add("is-hidden");const b=async s=>{try{if(s.preventDefault(),d=u.elements.user_query.value.trim(),d==="")return;i=1,p.classList.remove("is-hidden"),c.innerHTML="";const t=await f(d,i);if(t.data.total===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c.innerHTML="",l.classList.add("is-hidden");return}const a=t.data.hits.map(o=>y(o)).join("");c.innerHTML=a,l.classList.remove("is-hidden"),g.refresh(),Math.ceil(t.data.totalHits/15)===i&&(l.classList.add("is-hidden"),n.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"}))}catch(t){n.error({message:t.message,position:"topRight"})}finally{u.reset(),p.classList.add("is-hidden")}},v=async s=>{try{i++;const t=await f(d,i),a=t.data.hits.map(e=>y(e)).join("");c.insertAdjacentHTML("beforeend",a);const o=()=>{const{height:e}=c.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})};g.refresh(),o(),Math.ceil(t.data.totalHits/15)===i&&(l.classList.add("is-hidden"),n.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"}))}catch{n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}finally{p.classList.add("is-hidden")}};u.addEventListener("submit",b);l.addEventListener("click",v);
//# sourceMappingURL=index.js.map
